# Generated by Django 3.0 on 2019-12-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadedFile', models.FileField(blank=True, null=True, upload_to='')),
                ('fileContents', models.TextField()),
            ],
        ),
    ]
