# Generated by Django 3.0 on 2019-12-17 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsanalyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GraphAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LineProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_lineNumber', models.IntegerField()),
                ('_messageDate', models.DateTimeField()),
                ('_messageSender', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyTimingAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_lineNumber', models.IntegerField()),
                ('_messageSender', models.CharField(max_length=500)),
                ('_replyDurationHours', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppTextFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_filePath', models.CharField(max_length=260)),
                ('_fileName', models.CharField(max_length=260)),
                ('_fileContents', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='FileProcessing',
        ),
        migrations.AddField(
            model_name='message',
            name='_whatsAppTextFile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsanalyzer.WhatsAppTextFile'),
        ),
    ]
