# Generated by Django 3.0 on 2019-12-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsanalyzer', '0002_auto_20191217_1730'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountAnalysis',
        ),
        migrations.DeleteModel(
            name='GraphAnalysis',
        ),
        migrations.DeleteModel(
            name='LineProcessing',
        ),
        migrations.DeleteModel(
            name='ReplyTimingAnalysis',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='_lineNumber',
            new_name='lineNumber',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='_messageDate',
            new_name='messageDate',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='_whatsAppTextFile',
            new_name='whatsAppTextFile',
        ),
        migrations.RenameField(
            model_name='whatsapptextfile',
            old_name='_fileContents',
            new_name='fileContents',
        ),
        migrations.RenameField(
            model_name='whatsapptextfile',
            old_name='_fileName',
            new_name='fileName',
        ),
        migrations.RemoveField(
            model_name='message',
            name='_messageSender',
        ),
        migrations.RemoveField(
            model_name='whatsapptextfile',
            name='_filePath',
        ),
        migrations.AddField(
            model_name='message',
            name='messageSender',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='messageText',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsapptextfile',
            name='fileType',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
