# Generated by Django 3.0 on 2019-12-23 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsanalyzer', '0003_auto_20191223_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='whatsAppTextFile',
        ),
    ]
