# Generated by Django 2.2.2 on 2020-01-04 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsanalyzer', '0004_remove_message_whatsapptextfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='WhatsAppTextFile',
        ),
    ]
